baseURL = "https://dvdvgt.github.io/"
languageCode = "en-us"
title = "> echo 'David's Stuff' ▁"

theme = "hugo-coder"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "David Voigt"
  info = "B.Sc. Computer Science Student"
  description = "My personal website"
  keywords = "blog,developer,personal"
  avatarurl = "/images/man.svg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/images/terminal32x32.png"
  favicon_16 = "/images/terminal16x16.png"

  #footercontent = "Enter a text here."
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2020

  enableTwemoji = true

  rtl = false

  # Specify light/dark colorscheme
  # Supported values:
  # "auto" (use preference set by browser)
  # "dark" (dark background, light foreground)
  # "light" (light background, dark foreground) (default)
  colorScheme = "auto"

  # Hide the toggle button, along with the associated vertical divider
  hideColorSchemeToggle = false

  # Series see also post count
  maxSeeAlsoItems = 5

  # Custom CSS
  customCSS = []

  # Custom SCSS
  customSCSS = []

  # Custom JS
  customJS = []


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"
  lang = "lang"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/dvdvgt/"

[[params.social]]
  name = "Gitea"
  icon = "fa fa-gitea fa-2x"
  weight = 1
  url = "https://gitea.ddnss.de"

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"
